package JFrame;

import java.util.HashSet;
import practico4_v2.Alumno;
import practico4_v2.Materia;

public class Colegio extends javax.swing.JFrame {

    public static HashSet<Alumno> alumnos = new HashSet<>();
    public static HashSet<Materia> materias = new HashSet<>();

    /**
     * Creates new form Menu_Principal
     */
    public Colegio() {

        Materia InglesI = new Materia(1, "Ingles I", "Primero");
        Materia Matematicas = new Materia(3, "Matematicas", "Primero");
        Materia Laboratorio1 = new Materia(2, "Laboratorio 1", "Primero");

        materias.add(InglesI);

        materias.add(Matematicas);

        materias.add(Laboratorio1);
        Alumno a1 = new Alumno(1001, "López", "Martin");
        Alumno a2 = new Alumno(1002, "Martínez", "Brenda");

        alumnos.add(a1);

        alumnos.add(a2);

        a1.agregarMateria(InglesI);

        a1.agregarMateria(Matematicas);

        a1.agregarMateria(Laboratorio1);

        // 4. Inscribir a Martínez en las 3 materias y volver a inscribirlo en Laboratorio 1
        a2.agregarMateria(InglesI);

        a2.agregarMateria(Matematicas);

        a2.agregarMateria(Laboratorio1);

        a2.agregarMateria(Laboratorio1);

        System.out.println(
                "López está inscripto en " + a1.cantidadMaterias() + " materias.");
        System.out.println(
                "Martínez está inscripto en " + a2.cantidadMaterias() + " materias.");
        initComponents();
        
        Escritorio.removeAll();
        Escritorio.repaint();
        Formulario_Inscripcion Finscripcion = new Formulario_Inscripcion();
        Finscripcion.setVisible(true);
        Escritorio.add(Finscripcion);
        Escritorio.moveToFront(Finscripcion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        JBAlumno = new javax.swing.JMenu();
        JMalumno = new javax.swing.JMenuItem();
        JBmaterias = new javax.swing.JMenu();
        JMmaterias = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        JMinscripcion = new javax.swing.JMenuItem();
        ColegioMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        JBAlumno.setText("Alumno");

        JMalumno.setText("Agregar Alumno");
        JMalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMalumnoActionPerformed(evt);
            }
        });
        JBAlumno.add(JMalumno);

        jMenuBar1.add(JBAlumno);

        JBmaterias.setText("Materia");

        JMmaterias.setText("Agregar Materia");
        JMmaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMmateriasActionPerformed(evt);
            }
        });
        JBmaterias.add(JMmaterias);

        jMenuBar1.add(JBmaterias);

        jMenu1.setText("Registro");

        JMinscripcion.setText("Incripcion");
        JMinscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMinscripcionActionPerformed(evt);
            }
        });
        jMenu1.add(JMinscripcion);

        jMenuBar1.add(jMenu1);

        ColegioMenu.setText("Salir");
        ColegioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColegioMenuActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cerrar aplicación");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ColegioMenu.add(jMenuItem1);

        jMenuBar1.add(ColegioMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMinscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMinscripcionActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        Formulario_Inscripcion Finscripcion = new Formulario_Inscripcion();
        Finscripcion.setVisible(true);
        Escritorio.add(Finscripcion);
        Escritorio.moveToFront(Finscripcion);
    }//GEN-LAST:event_JMinscripcionActionPerformed

    private void JMalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMalumnoActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        Formulario_Alumnos Falumnos = new Formulario_Alumnos();
        Falumnos.setVisible(true);
        Escritorio.add(Falumnos);
        Escritorio.moveToFront(Falumnos);
    }//GEN-LAST:event_JMalumnoActionPerformed

    private void JMmateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMmateriasActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        Formulario_Materias Fmaterias = new Formulario_Materias();
        Fmaterias.setVisible(true);
        Escritorio.add(Fmaterias);
        Escritorio.moveToFront(Fmaterias);
    }//GEN-LAST:event_JMmateriasActionPerformed

    private void ColegioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColegioMenuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ColegioMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colegio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colegio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colegio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colegio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colegio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ColegioMenu;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu JBAlumno;
    private javax.swing.JMenu JBmaterias;
    private javax.swing.JMenuItem JMalumno;
    private javax.swing.JMenuItem JMinscripcion;
    private javax.swing.JMenuItem JMmaterias;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
